services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"

  test:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["sh", "-c", "npx prisma generate && npm test"]
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  pg_data: